from __future__ import annotations
import json
import logging
from schemas.state import DesignState
from agents.base import AgentProtocol
from utils.llm_utils import call_llm

VALID_ERROR_TYPES = {"LOGIC_ERROR", "PART_ERROR", "BOTH", "NONE"}
PASS_SCORE_THRESHOLD = 0.80
FAIL_SCORE_THRESHOLD = 0.60


def _extract_score(best_topo: dict | None) -> float | None:
    if not best_topo:
        return None
    score = best_topo.get("score")
    if score is None and isinstance(best_topo.get("benchmark_report"), dict):
        score = best_topo["benchmark_report"].get("score")
    try:
        return float(score)
    except (TypeError, ValueError):
        return None


def _benchmark_report(best_topo: dict | None) -> dict:
    if not best_topo:
        return {
            "score": None,
            "mapping_status": "missing",
            "details": [],
            "notes": "No valid mapping topology was generated by Cello/ODE Simulator.",
        }
    report = {}
    if isinstance(best_topo.get("benchmark_report"), dict):
        report.update(best_topo["benchmark_report"])
    if "score" not in report:
        report["score"] = best_topo.get("score")
    report["mapping_status"] = best_topo.get("mapping_status", report.get("mapping_status", "unknown"))
    report["ode_status"] = best_topo.get("ode_status", report.get("ode_status", "unknown"))
    report["details"] = report.get("details", best_topo.get("details", []))
    return report


def _routing_target(error_type: str) -> str:
    if error_type in {"LOGIC_ERROR", "BOTH"}:
        return "Builder"
    if error_type == "PART_ERROR":
        return "Translator"
    return "Consolidator"

class CriticAgent(AgentProtocol):
    def __init__(
        self,
        api_key: str | None,
        model_name: str,
        api_base: str | None = None,
        **kwargs
    ):
        self.api_key = api_key
        self.model_name = model_name
        self.api_base = api_base
        self.kwargs = kwargs

    def run(self, state: DesignState) -> DesignState:
        node = None
        if state.current_node_id and state.current_node_id in state.tree_nodes:
            node = state.tree_nodes[state.current_node_id]
            
        proposals = []
        if node:
            proposals = node.logic_proposals
            best_topo = node.best_topology
        else:
            proposals = state.logic_proposals
            best_topo = state.best_topology

        benchmark_report = _benchmark_report(best_topo)
        observed_score = _extract_score(best_topo)

        system_prompt = f"""You are a rigorous Synthetic Biology Critic Agent.
Your job is to evaluate the Builder's logic proposal, generated topology, and benchmark report.

Benchmark report contract:
- `score` is normalized from 0 to 1.
- If score < {FAIL_SCORE_THRESHOLD:.2f}, the design MUST fail with is_approved=false.
- If score >= {PASS_SCORE_THRESHOLD:.2f}, approve only when the logic also matches the user intent and the mapped topology is usable.
- Scores between {FAIL_SCORE_THRESHOLD:.2f} and {PASS_SCORE_THRESHOLD:.2f} require a clear routing decision.

Routing rules:
- Functional score is low, truth table does not satisfy intent, Boolean expression is wrong, or intent is misunderstood -> LOGIC_ERROR.
- Logic is acceptable but Cello mapping failed, kinetic/static plausibility is low, toxicity/part constraints are violated, or ODE dynamics are poor -> PART_ERROR.
- Logic and physical implementation are both problematic -> BOTH.
- Everything is acceptable -> NONE and is_approved=true.
- If the same class of problem cannot be repaired without extra user constraints, set requires_human_input=true and recoverable=false.

You MUST output ONLY a valid JSON object matching this schema:
{{
  "reasoning": "Step-by-step analysis",
  "score": 0.0,
  "benchmark_summary": "functional/kinetic/static/mapping interpretation",
  "is_approved": false,
  "error_type": "LOGIC_ERROR | PART_ERROR | BOTH | NONE",
  "routing_target": "Builder | Translator | Consolidator | Human",
  "recoverable": true,
  "requires_human_input": false,
  "feedback": "Specific instructions for Builder or Translator"
}}
"""
        user_content = f"Original Intent: {state.user_intent}\n"
        user_content += f"Logic Proposals: {proposals}\n"
        user_content += f"Benchmark Report: {benchmark_report}\n"
        user_content += f"Failed Attempt History: {state.failed_attempts}\n"
        if state.human_constraints:
            user_content += f"Human Constraints: {state.human_constraints}\n"
        if best_topo:
            user_content += f"Best Topology Mapping: {best_topo}\n"
        else:
            user_content += "No valid mapping topologies were generated by Cello/ODE Simulator.\n"
            
        response = call_llm(
            api_key=self.api_key,
            model_name=self.model_name,
            system_prompt=system_prompt,
            user_content=user_content,
            api_base=self.api_base,
            temperature=0.1
        )
        
        try:
            start = response.find("{")
            end = response.rfind("}")
            if start != -1 and end != -1:
                data = json.loads(response[start : end + 1])
                is_approved = data.get("is_approved", False)
                error_type = data.get("error_type", "BOTH")
                if error_type not in VALID_ERROR_TYPES:
                    logging.error("Critic returned invalid error_type: %s", error_type)
                    error_type = "BOTH"

                score = data.get("score", observed_score)
                try:
                    score = None if score is None else float(score)
                except (TypeError, ValueError):
                    score = observed_score

                if score is not None and score < FAIL_SCORE_THRESHOLD:
                    is_approved = False
                    if error_type == "NONE":
                        error_type = "PART_ERROR"
                if is_approved and error_type != "NONE":
                    is_approved = False
                if error_type == "NONE" and not is_approved:
                    error_type = "PART_ERROR"

                feedback = data.get("feedback", "No feedback provided.")
                requires_human_input = bool(data.get("requires_human_input", False))
                recoverable = bool(data.get("recoverable", True))
                if not recoverable:
                    requires_human_input = True
                routing_target = data.get("routing_target") or _routing_target(error_type)
                benchmark_summary = data.get("benchmark_summary", "")
                
                if node:
                    node.is_approved = is_approved
                    node.error_type = error_type
                    node.critic_feedbacks.append(feedback)
                    if score is not None:
                        node.score = score
                else:
                    state.is_approved = is_approved
                    state.error_type = error_type
                    state.critic_feedbacks.append(feedback)
                state.is_approved = is_approved
                state.error_type = error_type
                if requires_human_input:
                    state.requires_human_input = True
                    state.pause_reason = "critic_unrecoverable"
                    state.human_feedback_prompt = feedback
                data["error_type"] = error_type
                data["is_approved"] = is_approved
                data["score"] = score
                data["routing_target"] = routing_target
                data["benchmark_summary"] = benchmark_summary
            else:
                logging.error("Critic output is not JSON.")
                if node:
                    node.error_type = "BOTH"
                    node.critic_feedbacks.append("Critic evaluation failed.")
                state.error_type = "BOTH"
        except Exception as exc:
            logging.error(f"Critic JSON parse error: {exc}")
            if node:
                node.error_type = "BOTH"
                node.critic_feedbacks.append("Critic evaluation parsing failed.")
            state.error_type = "BOTH"

        return state
